@echo off
echo Stopping any old Streamlit processes...
taskkill /F /IM streamlit.exe >nul 2>&1
npx --yes kill-port 8501 >nul 2>&1
echo Activating virtual environment...
call .venv\Scripts\activate
echo Starting app.py on port 8501...
streamlit run app.py --server.port 8501
